find . -exec rename 's/Й/й/gu' {} +
find . -exec rename 's/Ц/ц/gu' {} +
find . -exec rename 's/У/у/gu' {} +
find . -exec rename 's/К/к/gu' {} +
find . -exec rename 's/Е/е/gu' {} +
find . -exec rename 's/Н/н/gu' {} +
find . -exec rename 's/Г/г/gu' {} +
find . -exec rename 's/Ш/ш/gu' {} +
find . -exec rename 's/Щ/щ/gu' {} +
find . -exec rename 's/З/з/gu' {} +
find . -exec rename 's/Х/х/gu' {} +
find . -exec rename 's/Ъ/ъ/gu' {} +
find . -exec rename 's/Ф/ф/gu' {} +
find . -exec rename 's/Ы/ы/gu' {} +
find . -exec rename 's/В/в/gu' {} +
find . -exec rename 's/А/а/gu' {} +
find . -exec rename 's/П/п/gu' {} +
find . -exec rename 's/Р/р/gu' {} +
find . -exec rename 's/О/о/gu' {} +
find . -exec rename 's/Л/л/gu' {} +
find . -exec rename 's/Д/д/gu' {} +
find . -exec rename 's/Ж/ж/gu' {} +
find . -exec rename 's/Э/э/gu' {} +
find . -exec rename 's/Я/я/gu' {} +
find . -exec rename 's/Ч/ч/gu' {} +
find . -exec rename 's/С/с/gu' {} +
find . -exec rename 's/М/м/gu' {} +
find . -exec rename 's/И/и/gu' {} +
find . -exec rename 's/Т/т/gu' {} +
find . -exec rename 's/Ь/ь/gu' {} +
find . -exec rename 's/Б/б/gu' {} +
find . -exec rename 's/Ю/ю/gu' {} +
find . -exec rename 's/»//gu' {} +
find . -exec rename 's/«//gu' {} +
find . -exec rename 's/ /-/gu' {} +
